AllCops:
  Exclude:
    - 'db/schema.rb'
# Offense count: 24
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 112

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/mock_data/slack_api.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/controllers/teams_controller_spec.rb'
# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

# Offense count: 4
Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Security/MarshalLoad:
  Exclude:
    - 'app/lib/encrypted_coder.rb'
    