# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6837536e18872c68276064f194bb0bcf0d7042504fb8dffbdbcbd267d3a7853f390c9243e56527cedfce983d43d90f79c97e5f02ce2e66568ceb318640993bdf

test:
  secret_key_base: 4cbcc83644f6ef0c03de5fb5f1ae4bbe1838f80da0d1d3134c39471bb1dcb3dcfe7b2604eab7790b08ad79ae0f347c3f0fba919716f8ea97f882a7be03a29042

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
